### ISSUE TITLE
Use API instead of direct access

### ISSUE THREAD

**Issue by daynaskully** [mbilokonsky/ambassador#8]

**Comment by mbilokonsky** [comment]
@daynaskully you are absolutely welcome to re-open this with some discussion of how you'd go about doing this, but I'm closing this issue as "won't fix" for now.

I don't see how to get the same functionality via the API, since it doesn't support querying the same kinds of information AFAICT. If you have information to the contrary please submit a PR, I'd love not to depend on database access!
